services:
  migrate:
    image: ${DOCKER_REGISTRY:-registry.localhost}/labs/migrate:${DOCKER_TAG:-latest}
    build:
      context: .
      dockerfile: migrate.dockerfile
      target: ${BUILD_TARGET:-dev}
      args:
        BUILD_TARGET: ${BUILD_TARGET:-dev}
        BUILD_CREATED: ${BUILD_CREATED:-}
        BUILD_VERSION: ${BUILD_VERSION:-}
        GIT_COMMIT: ${GIT_COMMIT:-}
    container_name: migrate
    network_mode: host
    stdin_open: true
    tty: true
    environment:
      DATABASE_URL: 'postgres://user:password@localhost:5433/dbname?sslmode=disable'
    volumes:
      - /etc/localtime:/etc/localtime:ro
