/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz
         * @description Health check endpoint.
         *
         *     Returns:
         *         HealthResponse: Indicates if the service is healthy.
         */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/livez": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Livez
         * @description Liveness check endpoint.
         *
         *     Returns:
         *         HealthResponse: Indicates if the service is alive.
         */
        get: operations["livez_livez_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readyz
         * @description Readiness check endpoint.
         *
         *     Returns:
         *         HealthResponse: Indicates if the service is ready to serve traffic.
         */
        get: operations["readyz_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teleop/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Teleop
         * @description Start teleoperation mode.
         *
         *     Transitions the system from IDLE to TELEOP state, allowing the operator to control the robot.
         *
         *     Args:
         *         teleop_service: Injected TeleopService dependency.
         *
         *     Returns:
         *         TeleopResponse: Result of the start teleoperation operation.
         *
         *     Raises:
         *         HTTPException: If the operation fails.
         */
        post: operations["start_teleop_api_v1_teleop_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teleop/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stop Teleop
         * @description Stop teleoperation mode.
         *
         *     Stops teleoperation and transitions the system back to IDLE state.
         *     Note: This is a custom transition not explicitly defined in the state machine.
         *
         *     Args:
         *         teleop_service: Injected TeleopService dependency.
         *
         *     Returns:
         *         TeleopResponse: Result of the stop teleoperation operation.
         *
         *     Raises:
         *         HTTPException: If the operation fails.
         */
        post: operations["stop_teleop_api_v1_teleop_stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teleop/start_syncing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Syncing
         * @description Start syncing
         *
         *     Transitions the system from READY to SYNCING state.
         *
         *     Args:
         *         teleop_service: Injected TeleopService dependency.
         *
         *     Returns:
         *         TeleopResponse: Result of the start syncing operation.
         *
         *     Raises:
         *         HTTPException: If the operation fails.
         */
        post: operations["start_syncing_api_v1_teleop_start_syncing_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teleop/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Teleop Status
         * @description Get the current status of teleoperation.
         *
         *     Args:
         *         teleop_service: Injected TeleopService dependency.
         *
         *     Returns:
         *         TeleopStatusResponse: Indicates if teleoperation is active or not.
         */
        get: operations["teleop_status_api_v1_teleop_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/episodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Episodes
         * @description Retrieve a list of episodes, optionally filtered by status or task.
         *
         *     Args:
         *         episode_service: Injected EpisodeService dependency.
         *         task_id: Optional task identifier to filter episodes.
         *         status: Optional status to filter episodes.
         *         processed: Optional processed status to filter episodes.
         *         shipped: Optional shipped status to filter episodes.
         *         limit: Maximum number of episodes to return (default 100).
         *         offset: Number of episodes to skip (default 0).
         *
         *     Returns:
         *         List of EpisodeResponse objects matching the filters.
         *
         *     Raises:
         *         HTTPException: If an error occurs during retrieval.
         */
        get: operations["get_episodes_api_v1_episodes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/episodes/{episode_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Episode By Id
         * @description Retrieve a single episode by its unique identifier.
         *
         *     Args:
         *         episode_id: Unique identifier for the episode.
         *         episode_service: Injected EpisodeService dependency.
         *
         *     Returns:
         *         EpisodeResponse: The episode data if found.
         *
         *     Raises:
         *         HTTPException: If the episode is not found or retrieval fails.
         */
        get: operations["get_episode_by_id_api_v1_episodes__episode_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Episode
         * @description Delete an episode and its recording by id.
         */
        delete: operations["delete_episode_api_v1_episodes__episode_id__delete"];
        options?: never;
        head?: never;
        /**
         * Patch Episode
         * @description Patch mutable fields of an episode (shipped, message).
         */
        patch: operations["patch_episode_api_v1_episodes__episode_id__patch"];
        trace?: never;
    };
    "/api/v1/recording/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Recording
         * @description Start a new recording for a given episode and task.
         *
         *     Args:
         *         task_id: Unique identifier for the task.
         *         recording_service: Injected RecordingService dependency.
         *
         *     Returns:
         *         StartRecordingResponse: Result of the start recording operation.
         *
         *     Raises:
         *         HTTPException: If the operation fails.
         */
        post: operations["start_recording_api_v1_recording_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recording/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stop Recording
         * @description Stop the current recording.
         *
         *     Args:
         *         recording_service: Injected RecordingService dependency.
         *
         *     Returns:
         *         StopRecordingResponse: Result of the stop recording operation.
         *
         *     Raises:
         *         HTTPException: If the operation fails.
         */
        post: operations["stop_recording_api_v1_recording_stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recording/save": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Save Recording
         * @description Save the current recording, with tags indicating success or failure.
         *
         *     Args:
         *         tags: Optional tags for the save operation (must be 'successful' or 'failed').
         *         label: Label for the episode (REVIEW_SUCCESS or REVIEW_FAILED).
         *         recording_service: Injected RecordingService dependency.
         *
         *     Returns:
         *         SaveRecordingResponse: Result of the save operation.
         *
         *     Raises:
         *         HTTPException: If the operation fails.
         */
        post: operations["save_recording_api_v1_recording_save_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recording/discard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Discard Recording
         * @description Discard the current recording.
         *
         *     Args:
         *         recording_service: Injected RecordingService dependency.
         *
         *     Returns:
         *         DiscardRecordingResponse: Result of the discard operation.
         *
         *     Raises:
         *         HTTPException: If the operation fails.
         */
        post: operations["discard_recording_api_v1_recording_discard_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Devices
         * @description Retrieve all available device information, optionally filtered by type.
         *
         *     Args:
         *         device_service: Injected DeviceService dependency.
         *         device_type: Optional device type filter from query parameter 'type'.
         *
         *     Returns:
         *         List[DeviceResponse]: List of device information objects.
         *
         *     Raises:
         *         HTTPException: If an error occurs while retrieving devices.
         */
        get: operations["get_devices_api_v1_devices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get System Info
         * @description Retrieve all available system information.
         *
         *     Args:
         *         system_service: Injected SystemService dependency.
         *
         *     Returns:
         *         SystemGetResponse: System information response object.
         *
         *     Raises:
         *         HTTPException: If an error occurs while retrieving system information.
         */
        get: operations["get_system_info_api_v1_system_info_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Tasks
         * @description List tasks with optional name filter.
         */
        get: operations["get_tasks_api_v1_tasks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Task
         * @description Get a single task by ID.
         */
        get: operations["get_task_api_v1_tasks__task_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Root
         * @description Root endpoint that returns basic service info.
         */
        get: operations["read_root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActiveEpisode
         * @description Represents an active episode summary.
         */
        ActiveEpisode: {
            /** Id */
            id: string;
            /** Status */
            status: string;
            /** Started On */
            started_on?: string | null;
            /** Task Id */
            task_id?: string | null;
        };
        /**
         * DeviceResponse
         * @description Response model for a device.
         */
        DeviceResponse: {
            /** Id */
            id: string;
            type: components["schemas"]["DeviceType"];
            status: components["schemas"]["DeviceStatus"];
            /** Config */
            config: {
                [key: string]: unknown;
            };
        };
        /**
         * DeviceStatus
         * @description Device status enum.
         * @enum {string}
         */
        DeviceStatus: "UNKNOWN" | "ONLINE" | "OFFLINE" | "ERROR";
        /**
         * DeviceType
         * @description Enum for device type.
         * @enum {string}
         */
        DeviceType: "TELEOP_ROBOT" | "REALSENSE_CAMERA" | "ZED_CAMERA" | "ROBOT_OBSERVER";
        /** DiscardRecordingResponse */
        DiscardRecordingResponse: {
            /** Status */
            status: string;
            /** Message */
            message: string;
        };
        /**
         * EpisodeDeleteResponse
         * @description Response model for deleting episode.
         */
        EpisodeDeleteResponse: {
            /** Status */
            status: string;
            /**
             * Message
             * @default
             */
            message: string;
        };
        /**
         * EpisodeLabel
         * @description Enumeration of labels for an episode.
         * @enum {string}
         */
        EpisodeLabel: "REVIEW_SUCCESS" | "REVIEW_FAILED";
        /**
         * EpisodePatchRequest
         * @description Request model used to patch episode fields (shipped and message).
         */
        EpisodePatchRequest: {
            processed?: components["schemas"]["EpisodeProcessed"] | null;
            shipped?: components["schemas"]["EpisodeShipped"] | null;
            /** Message */
            message?: string | null;
            /** Object Url */
            object_url?: string | null;
        };
        /**
         * EpisodeProcessed
         * @description Enumeration for episode processed status.
         * @enum {string}
         */
        EpisodeProcessed: "DEFAULT" | "SUCCESS" | "ERROR";
        /**
         * EpisodeResponse
         * @description Response model for episode endpoints.
         */
        EpisodeResponse: {
            /**
             * Episode Id
             * Format: uuid
             */
            episode_id: string;
            /**
             * Task Id
             * Format: uuid
             */
            task_id: string;
            /** Station Id */
            station_id: string;
            status: components["schemas"]["EpisodeStatus"];
            /**
             * Message
             * @default
             */
            message: string;
            /**
             * Tags
             * @default []
             */
            tags: string[];
            label?: components["schemas"]["EpisodeLabel"] | null;
            /** Created At */
            created_at?: string | null;
            /** Updated At */
            updated_at?: string | null;
            /** Duration Seconds */
            duration_seconds?: number | null;
            /** @default DEFAULT */
            processed: components["schemas"]["EpisodeProcessed"];
            /** @default DEFAULT */
            shipped: components["schemas"]["EpisodeShipped"];
            /** Object Url */
            object_url?: string | null;
        };
        /**
         * EpisodeShipped
         * @description Enumeration for episode shipped status.
         * @enum {string}
         */
        EpisodeShipped: "DEFAULT" | "SUCCESS" | "ERROR";
        /**
         * EpisodeStatus
         * @description Enum for episode status.
         * @enum {string}
         */
        EpisodeStatus: "INIT" | "RECORDING" | "RECORDED" | "SAVED" | "DISCARDED" | "ERROR";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Response model for health checks.
         */
        HealthResponse: {
            /** Status */
            status: string;
        };
        /** SaveRecordingResponse */
        SaveRecordingResponse: {
            /** Status */
            status: string;
            /** Message */
            message: string;
        };
        /** StartRecordingResponse */
        StartRecordingResponse: {
            /**
             * Episode Id
             * Format: uuid
             */
            episode_id: string;
            /** Status */
            status: string;
            /** Message */
            message: string;
        };
        /** StopRecordingResponse */
        StopRecordingResponse: {
            /** Status */
            status: string;
            /** Message */
            message: string;
        };
        /**
         * SystemGetResponse
         * @description Detailed system information model.
         */
        SystemGetResponse: {
            /** Workflow State */
            workflow_state: string;
            /** Recording State */
            recording_state: string;
            /** System Status */
            system_status: string;
            /** Station Id */
            station_id: string;
            active_episode?: components["schemas"]["ActiveEpisode"] | null;
        };
        /**
         * TaskResponse
         * @description Response model for tasks.
         */
        TaskResponse: {
            /**
             * Task Id
             * Format: uuid
             */
            task_id: string;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Version */
            version?: string | null;
            /** Language Instructions */
            language_instructions?: string[];
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
        };
        /**
         * TeleopResponse
         * @description Response model for teleoperation endpoints.
         */
        TeleopResponse: {
            /** Status */
            status: string;
            /** Message */
            message: string;
        };
        /**
         * TeleopStatusResponse
         * @description Response model for teleoperation status endpoint.
         */
        TeleopStatusResponse: {
            /** Status */
            status: string;
            /** Is Active */
            is_active: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    livez_livez_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    readyz_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    start_teleop_api_v1_teleop_start_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeleopResponse"];
                };
            };
        };
    };
    stop_teleop_api_v1_teleop_stop_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeleopResponse"];
                };
            };
        };
    };
    start_syncing_api_v1_teleop_start_syncing_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeleopResponse"];
                };
            };
        };
    };
    teleop_status_api_v1_teleop_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeleopStatusResponse"];
                };
            };
        };
    };
    get_episodes_api_v1_episodes_get: {
        parameters: {
            query?: {
                /**
                 * @description Optional task identifier to filter episodes.
                 * @example b06d85e1-c053-49db-acbb-685fc64ddf8a
                 */
                task_id?: string | null;
                status?: string | null;
                /** @description Optional processed filter: DEFAULT, SUCCESS, or ERROR */
                processed?: components["schemas"]["EpisodeProcessed"] | null;
                /** @description Optional shipped filter: DEFAULT, SUCCESS, or ERROR */
                shipped?: components["schemas"]["EpisodeShipped"] | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EpisodeResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_episode_by_id_api_v1_episodes__episode_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                episode_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EpisodeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_episode_api_v1_episodes__episode_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                episode_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EpisodeDeleteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_episode_api_v1_episodes__episode_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                episode_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EpisodePatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EpisodeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_recording_api_v1_recording_start_post: {
        parameters: {
            query: {
                /**
                 * @description Unique identifier for the task.
                 * @example b06d85e1-c053-49db-acbb-685fc64ddf8a
                 */
                task_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StartRecordingResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stop_recording_api_v1_recording_stop_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StopRecordingResponse"];
                };
            };
        };
    };
    save_recording_api_v1_recording_save_post: {
        parameters: {
            query: {
                /** @description Label for the episode */
                label: components["schemas"]["EpisodeLabel"];
                /** @description Tags for the save operation */
                tags?: string[] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaveRecordingResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    discard_recording_api_v1_recording_discard_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiscardRecordingResponse"];
                };
            };
        };
    };
    get_devices_api_v1_devices_get: {
        parameters: {
            query?: {
                /** @description Filter devices by type */
                type?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_system_info_api_v1_system_info_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemGetResponse"];
                };
            };
        };
    };
    get_tasks_api_v1_tasks_get: {
        parameters: {
            query?: {
                /** @description Filter tasks by exact name */
                name?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_task_api_v1_tasks__task_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
